# wiki/_config.yml

title: knowledge-base
description: This wiki is a collection of information on how to run Star Citizen on Linux, as well as our tips and tricks!
baseurl: ""
permalink: /:path/

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

color_scheme: dark

nav_sort: case_insensitive

include:
  - "*.md"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: purple
  highlight:
    title: highlight
    color: yellow