# wiki/_config.yml

logo: "/assets/images/lug_logo_finished_by_polymachairoplacida.png"
title: Star Citizen LUG Wiki
description: The Star Citizen Linux Users Group Wiki. Everything you need to know to run Star Citizen on Linux!
baseurl: ""
permalink: /:path

remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

color_scheme: dark

nav_sort: case_insensitive

aux_links:
  "Join our Star Citizen Org":
    - "https://robertsspaceindustries.com/orgs/LUG"
  "Contribute to this wiki":
    - "https://github.com/starcitizen-lug/knowledge-base"

include:
  - "*.md"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red
